version: "3.7"
services:
  app:
    build: .
    ports:
      - 5000:8001
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 33061:3306
  redis:
    image: redis
    ports:
      - 63791:6379
  adminer:
    image: adminer
    ports:
      - 8002:8080
  phpredisadmin:
    build:
      dockerfile: PhpredisadminDockerfile
      context: .
    environment:
      REDIS_1_HOST: redis
    ports:
      - 8003:80